version: "3.8"

services:
  app:
    build: .
    container_name: flask-audio
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      - FLASK_ENV=development  # Altere para production se necessário
